/**
 * Downloads every photo referenced in src/data into public/images so the site works
 * without any external CDN (handy for offline demos and for networks where Unsplash
 * is unreachable). Tries Unsplash first, then a keyword-based Flickr lookup.
 *
 * Usage: npm run images:download
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SRC = new URL('../src', import.meta.url).pathname
const OUT = new URL('../public/images', import.meta.url).pathname
const MANIFEST = join(SRC, 'generated', 'local-images.ts')
const WIDTHS = [800, 1600]
const PHOTO_RE = /photo-\d{13}-[0-9a-f]{12}/g

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (/\.tsx?$/.test(entry) && !full.includes('generated')) out.push(full)
  }
  return out
}

/** Finds a photo id together with the nearest `keyword:` field declared in the same object. */
function collectPhotos() {
  const photos = new Map()
  for (const file of walk(SRC)) {
    const source = readFileSync(file, 'utf8')
    const ids = [...source.matchAll(PHOTO_RE)]
    for (const match of ids) {
      const before = source.slice(0, match.index)
      const keyword = [...before.matchAll(/keyword: '([^']+)'/g)].at(-1)?.[1]
      const inline = [...before.matchAll(/fallbackKeywords="([^"]+)"/g)].at(-1)?.[1]
      const cityMatch = [...before.matchAll(/cities: \[([^\]]+)\]/g)].at(-1)?.[1]
      const city = cityMatch?.match(/'([^']+)'/)?.[1]
      if (!photos.has(match[0])) photos.set(match[0], keyword ?? inline ?? city ?? 'travel')
    }
  }
  return photos
}

function lock(photo) {
  let hash = 0
  for (const char of photo) hash = (hash * 31 + char.charCodeAt(0)) >>> 0
  return (hash % 9000) + 1
}

async function fetchImage(url) {
  const response = await fetch(url, { redirect: 'follow' })
  if (!response.ok) throw new Error(`HTTP ${response.status}`)
  const type = response.headers.get('content-type') ?? ''
  if (!type.startsWith('image/')) throw new Error(`not an image (${type})`)
  return { buffer: Buffer.from(await response.arrayBuffer()), ext: type.includes('webp') ? 'webp' : 'jpg' }
}

async function download(photo, keyword) {
  const attempts = [
    (w) => `https://images.unsplash.com/${photo}?auto=format&fit=crop&fm=webp&w=${w}&q=78`,
    (w) => `https://loremflickr.com/${w}/${Math.round(w * 0.625)}/${encodeURIComponent(keyword)}?lock=${lock(photo)}`,
  ]
  for (const build of attempts) {
    try {
      const files = await Promise.all(WIDTHS.map((w) => fetchImage(build(w))))
      const ext = files[0].ext
      files.forEach((file, i) => writeFileSync(join(OUT, `${photo}-${WIDTHS[i]}.${ext}`), file.buffer))
      return { ext, source: build(1600).includes('unsplash') ? 'unsplash' : 'flickr' }
    } catch (error) {
      console.warn(`  ↻ ${photo}: ${error.message}, пробую следующий источник`)
    }
  }
  return null
}

mkdirSync(OUT, { recursive: true })
const photos = collectPhotos()
console.log(`Фотографий для загрузки: ${photos.size}`)

const manifest = {}
let index = 0
for (const [photo, keyword] of photos) {
  index += 1
  const existing = WIDTHS.every((w) => ['webp', 'jpg'].some((ext) => existsSync(join(OUT, `${photo}-${w}.${ext}`))))
  if (existing) {
    manifest[photo] = existsSync(join(OUT, `${photo}-1600.webp`)) ? 'webp' : 'jpg'
    console.log(`  ✓ [${index}/${photos.size}] ${photo} уже загружено`)
    continue
  }
  const result = await download(photo, keyword)
  if (result) {
    manifest[photo] = result.ext
    console.log(`  ✓ [${index}/${photos.size}] ${photo} (${result.source})`)
  } else {
    console.error(`  ✗ [${index}/${photos.size}] ${photo} — не удалось загрузить`)
  }
}

const entries = Object.entries(manifest)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, ext]) => `  '${id}': '${ext}',`)
  .join('\n')
writeFileSync(
  MANIFEST,
  `/**\n * Photos downloaded into public/images by \`npm run images:download\`.\n * Maps an Unsplash photo id to the saved file extension. Regenerated by the script — do not edit by hand.\n */\nexport const localImages: Readonly<Record<string, 'webp' | 'jpg'>> = {\n${entries}\n}\n`,
)
console.log(`\nГотово: ${entries.length} из ${photos.size} фотографий сохранено в public/images, манифест обновлён.`)
if (entries.length < photos.size) process.exit(1)
