/**
 * Downloads every asset listed in public/media/media-manifest.json into public/media/…
 * and regenerates src/generated/local-media.ts so components prefer the local copies.
 *
 * Run on a machine with open internet access:  npm run media:download
 * Items that cannot be fetched keep their remote URL — nothing is ever removed from the manifest.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const MANIFEST_PATH = join(ROOT, 'public/media/media-manifest.json')
const GENERATED = join(ROOT, 'src/generated/local-media.ts')
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
const items = [...manifest.images, ...manifest.videos]

async function fetchBinary(url) {
  const response = await fetch(url, { redirect: 'follow', headers: { 'user-agent': UA } })
  if (!response.ok) throw new Error(`HTTP ${response.status}`)
  const type = response.headers.get('content-type') ?? ''
  if (!/^(image|video)\//.test(type)) throw new Error(`unexpected content-type ${type}`)
  const buffer = Buffer.from(await response.arrayBuffer())
  // YouTube answers 200 with a tiny grey placeholder for missing thumbnails — treat as failure.
  if (buffer.length < 2048) throw new Error('placeholder-sized response')
  return buffer
}

let ok = 0
let failed = 0
for (const [i, item] of items.entries()) {
  if (!item.localPath || !item.originalUrl) continue
  const target = join(ROOT, 'public', item.localPath)
  if (existsSync(target)) {
    item.downloaded = true
    ok += 1
    continue
  }
  const candidates = [item.originalUrl, ...(item.fallbackUrls ?? [])]
  let saved = false
  for (const url of candidates) {
    try {
      const buffer = await fetchBinary(url)
      mkdirSync(dirname(target), { recursive: true })
      writeFileSync(target, buffer)
      console.log(`  ✓ [${i + 1}/${items.length}] ${item.localPath} ← ${url}`)
      saved = true
      break
    } catch (error) {
      console.warn(`  ↻ ${url}: ${error.message}`)
    }
  }
  item.downloaded = saved
  if (saved) ok += 1
  else {
    failed += 1
    console.error(`  ✗ [${i + 1}/${items.length}] ${item.localPath} — не удалось скачать, URL сохранён`)
  }
}

writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`)

const local = items.filter((item) => item.downloaded && item.localPath).map((item) => `  '${item.localPath}',`)
writeFileSync(
  GENERATED,
  `/**\n * Files that exist under public/media, regenerated by \`npm run media:download\`.\n * Components prefer these over remote URLs. Do not edit by hand.\n */\nexport const localMedia: ReadonlySet<string> = new Set<string>([\n${local.join('\n')}\n])\n`,
)
console.log(`\nГотово: ${ok} скачано, ${failed} недоступно. Манифест и src/generated/local-media.ts обновлены.`)
if (failed) process.exit(1)
